name:                difference-monoid
version:             0.1.0.0
github:              "oisdk/difference-monoid"
license:             MIT
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2018 Donnacha Oisín Kidney"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/oisdk/difference-monoid#readme>

dependencies:
- base >= 4.7 && < 5
- groups
- deepseq
- adjunctions
- distributive
- semigroupoids
- comonad

library:
  source-dirs: src

ghc-options:
- -Wall
- -fwarn-incomplete-record-updates
- -fwarn-incomplete-uni-patterns
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
    - -fwarn-redundant-constraints
    - -Wcompat

tests:
  difference-monoid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - difference-monoid
    - hedgehog
    - containers
    - hedgehog-checkers
  difference-monoid-doctests:
    main:                doctests.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    dependencies:
    - difference-monoid
    - doctest
    - QuickCheck

benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - difference-monoid
    - criterion
    - random
